version: "3.8"

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  app:
    image: python:3.9-alpine
    depends_on:
      - redis
    working_dir: /src/usr/app
    volumes:
      - ./:/src/usr/app
    command: ['tail', '-f', '/dev/null']

